# Generated by Django 4.1.7 on 2023-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='preisProTag',
            field=models.IntegerField(default=15),
        ),
    ]
