# Generated by Django 4.1.7 on 2023-03-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vehicles_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vName', models.CharField(max_length=30)),
                ('nName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='preisProTag',
            field=models.IntegerField(default=20),
        ),
    ]
