# Generated by Django 4.1.7 on 2023-03-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_alter_vehicles_preisprotag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eMail',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='telNr',
            field=models.IntegerField(default=1234),
        ),
    ]
