# Generated by Django 4.1.7 on 2023-03-03 15:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(choices=[('EB', 'E-BIKE'), ('ES', 'E-Scooter'), ('ER', 'E-Roller')], default='EB', max_length=2, primary_key=True, serialize=False)),
                ('price', models.CharField(choices=[('10', 'Bike Price'), ('10', 'Scooter Price'), ('15', 'Roller Price')], default='10', max_length=2)),
                ('power', models.CharField(default='1', max_length=2)),
                ('distance', models.CharField(default='100', max_length=3)),
                ('weight', models.CharField(default='10', max_length=3)),
                ('wheelsize', models.CharField(default='24', max_length=2)),
                ('Beschreibung', models.CharField(default='Hier steht die Beschreibung', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='preisProTag',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='vid',
            field=models.IntegerField(default=0, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Buchungstabelle',
            fields=[
                ('bid', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('tstart', models.DateField(default=datetime.timezone)),
                ('tend', models.DateField(default=datetime.timezone)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='vehicles',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
    ]
