# Generated by Django 4.1.7 on 2023-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_type_remove_user_id_remove_vehicles_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchungstabelle',
            name='bid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
