# Generated by Django 4.1.7 on 2023-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_buchungstabelle_bid_alter_user_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchungstabelle',
            name='tend',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='buchungstabelle',
            name='tstart',
            field=models.IntegerField(default=1),
        ),
    ]
