# Generated by Django 4.1.7 on 2023-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_buchungstabelle_tend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('E-Bike', 'E-BIKE'), ('E-Scooter', 'E-Scooter'), ('E-Roller', 'E-Roller')], default='E-Bike', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
