# Generated by Django 4.1.7 on 2023-03-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_vehicles_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=21)),
                ('strasse', models.CharField(max_length=50)),
                ('nummer', models.IntegerField()),
                ('plz', models.IntegerField()),
                ('ort', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='standort',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='lid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.location'),
        ),
    ]
