# Generated by Django 4.1.7 on 2023-03-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(default='e-Bike.jpg', upload_to='main\\static\\images\\detailpage\\static'),
        ),
    ]
