# Generated by Django 4.1.7 on 2023-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='Beschreibung',
            field=models.TextField(default='Hier steht die Beschreibung'),
        ),
        migrations.AlterField(
            model_name='type',
            name='price',
            field=models.CharField(choices=[('9', 'Bike Price'), ('6', 'Scooter Price'), ('18', 'Roller Price')], default='9', max_length=2),
        ),
    ]
