# Generated by Django 4.1.7 on 2023-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_type_beschreibung_alter_type_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchungstabelle',
            name='tend',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='buchungstabelle',
            name='tstart',
            field=models.DateField(),
        ),
    ]
