# Generated by Django 4.1.7 on 2023-04-11 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_alter_buchungstabelle_tend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='EMailAdresse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Nachname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Vorname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telNr',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
